### ISSUE TITLE
Settings key/button confusion

### ISSUE THREAD

**Issue by CP44** [ihsoft/KAS#101]
Version from KSP log: KAS v1.0.5204.25652

The default config file matched this format...
http://docs.unity3d.com/Manual/ConventionalGameInput.html
... meaning that tab worked in the following format:
toogleKey = tab
("toogleKey" is what the settings file is using)
On the good side, this means that joystick buttons did work in "any" and "specific" formats, ex.
toogleKey = joystick 1 button 0

The problem I originally encountered was that I could not get quote/apostrophe/singlequote/doublequote to be accepted in any format I tried...
the result is generally a continuous stream of the following message in the KSP debug log...
UnityException: Input Key named: "quote" is unknown

The following reference did not seem to help:
http://docs.unity3d.com/ScriptReference/KeyCode.html

**Comment by ihsoft** [comment]
The existing approach only supports keys that have character representation. It needs to be changed to KeyCode to support all game keys.
