### ISSUE TITLE
Wheels are wobbly after attachment

### ISSUE THREAD

**Issue by Zyles** [ihsoft/KAS#159]
I have a weird issue on a rover I built.

I used the mod [Buffalo](http://forum.kerbalspaceprogram.com/index.php?/topic/122617-105-buffalo-nasa-inspired-msev-fly-like-jetman-yves-rossy-with-the-jetwing/). Attached the wheels to a base that comes with the mod. Then I detached the wheel on the runway and attached it again.

Now when I use the rover that particular wheel is very unstable and wobbly. Like it is not attached properly.

**Comment by enceos** [comment]
I believe you used the surface attachment, not the node attachment. Surface attachment is weak when one of the parts is very light.

**Comment by sharpmaster** [comment]
I got this problem. I used the node attachment.

**Comment by ihsoft** [comment]
@sharpmaster How exactly did you use KAS to attach the wheels? As far as I'm concerned KAS doesn't let parts (e.g. wheels) to be attached.

**Comment by sharpmaster** [comment]
Excuse me. I inattentively read the first message. My problem is different. Probably is not essential.
