### ISSUE TITLE
[feature] support pushing off/throwing away of parts

### ISSUE THREAD

**Issue by tfischer4765** [ihsoft/KAS#160]
**Motivation:** When a part is held in grab mode, I can only drop it when it's in contact with something else. In orbit, that can have undesirable consequences, e.g. once when removing a vanity cover on a docking node, I "dropped" it onto the surface of the craft, resulting in the parts intersecting, the vanity cover shooting off in one direction, the kerbal in question in another direction and the ship madly spinning from the impulse. What I currently can't do is just "let go" of the part.

**Proposal:** When a grabbed part in place mode is hovered over the kerbal grabbing it, the ghost representation starts orbiting the kerbal on a spherical virtual "buble" surrounding the kerbal. The Action hint shows "Push off - Press P to push off in this direction". When P is pressed, the part is placed where it currently is shown and accelerated along a vector perpendicular to the virtual bubble's surface by (suggestion) .2 m/s

**Comment by ihsoft** [comment]
What's the benefit in accelerating the part? Once it started moved you still need to catch and attach/store it.

Btw, if bouncing is the main problem you can use offset hotkeys B/N to avoid close contact of the dropped part and the surface.

**Comment by tfischer4765** [comment]
To answer your question, accelerating is a vital component both in pushing something off as well as in throwing it. To throw or push something without accelerating it is called "letting go". :smile:  That would probably work well enough in some scenarios, but it is not quite the same. (If you don't get that quip, I refer you the issue title.) 

I'll have to try  the B/N keys to see if that is a feasible workaround.

**Comment by ihsoft** [comment]
I understand physical consequences of accelerating an object :) The question was: **why** do you need it? Let's say you've accelerated a part in some direction... now what? What was the intent, and what is the expected result? I doubt the intent was just letting things flying.

In real life random objects floating around a space station is a big problem so, people try to do quite the opposite: not let things "go". Are you trying to dispose a part this way? Or it's your idea on how to move bulky components between distant edges of the station?

**Comment by tfischer4765** [comment]
You doubt wrongly, it was exactly my intent to let things fly. And yes, I know all about Kessler Syndrome, micrometeorites and how it's generally a bad idea to litter in space, but firstly, that is reality and this is a game, and secondly, I'm thinking in kerbal here, and kerbals definitely **would** throw parts what they don't need any more over their shoulder. Even with both hands. Even without a lifeline. Get my drift?

Ok, let's be serious here a minute. The whole idea is indeed to simulate pushing or throwing a part in a certain direction. My original intention was indeed orbital trash disposal, or at least that was what spawned the idea, because as I said, I had no place to stick that hatch cover since it didn't fit in my pocket. Now that you mention it, the functionality could have other applications, especially in low-gravity environments. In microgravity, it is probably not a good idea to throw bulky parts from one end of a station to another, but on a moon, that might be a feasible if hard-to-control means of material transfer.

**Comment by tfischer4765** [comment]
By now I've tried out the B/N keys and found they do **not** fill that gap.

I've given it some more thought and found that acceleration wouldn't strictly be necessary as long as I had the option to "park" parts in microgravity next to myself. That would be even better than pushing them away, because I can always do that with a little eva thrust. What's not good - I've tried again - is to just detach the part and let drift move it away, that can lead to the undesirable side effects mentioned above.

**Comment by enceos** [comment]
@tfischer4765 have you tried dropping the part on Kerbal's body? It's exactly what you need. The part will get the same momentum the kerbal has. Intersection with Kerbal model is not deadly, I've almost never experienced a push on Kerbal when dropping parts on him.
