### ISSUE TITLE
Moving over terrain

### ISSUE THREAD

**Issue by MaartenvB123** [ihsoft/KAS#162]
debug log spams this
[Warning]: [KAS] Warning ! ActiveVessel is landed and heightFromTerrain are negative (-1) 

any way to fix this so im orbiting again

Edit:
ok i got some progress on how hyperedit fixes the problem
so first you get the warning then if you use hyperedit to get a orbit it does this:

-HyperEdit: Set ActiveVessel.Landed = false
-Packing Untitled Space Craft Probe for orbit
-HyperEdit: Orbit "Active vessel" changed to: inc=0 ecc=0 sma=700876.896144478 lan=0 argpe=0 mep=0 epoch=0 refbody=Kerbin
-Unpacking Untitled Space Craft Probe

the first line of the log is important "Set ActiveVessel.Landed = false"
 and it tells me im using a older version but im up-to-date

**Comment by ihsoft** [comment]
What did you do to trigger the error? Was you attaching parts on the orbit? If yes then what parts exactly? What are other consequences except the spam in the log?

**Comment by MaartenvB123** [comment]
Docking, eva boarding and placing parts 
(in my case a radiator) which triggered the bug and made the space station sit still in space but nellin kerman was not so he flew off at a speed of 2100 m/s still in a orbit around kerbin. Had to rescue him before he came back around and collide with the station. Had to use hyperedit which also seems to fix the problem because its sets it to false but its annoying having to do it every time it happens so any other way of fixing it.

**Comment by MaartenvB123** [comment]
Also makes the craft shake, no warp and no orbit

**Comment by ihsoft** [comment]
So, I've tried to some activity on the orbit it works fine to me. I may guess it's a mods conflict. Could you please find a stable reproducing scenario and check the logs when it happens?
