### ISSUE TITLE
Introduce flexible connections

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KAS#166]
When connecting modules in a ground base most of the time people need just make them exchanging resources. Usual pipe link creates a fixed joint that tries to keep all the modules in a whole piece which is challenging given the physics changes in Unity 5 and artifacts in surface colliders.

Connections that allow modules moving at some extent is a good solution for a common task. `SpringJoint` looks promising here. With small spring force and strong attachment points it will allow modules to move on small distances without breaking connection. This should be enough to compensate physics calculation errors.

**Comment by Somzer** [comment]
Ah yes, connector ports have also caused me a headache; upon connection, my lander's (small) landing legs turned to dust, my (KIS) surface attached ground pylon's connection to the ground was undone, as was the pylon's connection with the connector ports, sending the pylon flying, and connecting two medium/large sized spaceships resulted in some interesting, constantly escalating oscillating/wobbling ultimately resulting in the violent deconstruction of both vessels.

The cable of winches are "flexible", using it and connector ports to dock two vessels to transfer fuel (/to share the resource pool of vessels) seems to be a usable solution, but it would be great if we had flexible connection between two connector ports.

**Comment by ihsoft** [comment]
This is targeted to KAS 1.0. All rigid joints in 1.0 will support stock joints. There will be also unrestricted joins (e.g. TJ-2).
