### ISSUE TITLE
Unable to use winch with attached in VAB parts with wheels.

### ISSUE THREAD

**Issue by Hussky-66** [ihsoft/KAS#191]
Unable to extend winch wire, if any part connected to them in VAB have any wheels. 
When pressing extend or release in winch menu, the part moving down for a millimeter and nothing more happens. The only way to unattach this part ingame is press "release", then right click on connector port and "unplug", part will fall down with free wire.

**Comment by ihsoft** [comment]
That's due to KSP 1.2 new feature with autostruts. For now workaround is not attaching objects to winch in VAB if vessel has wheels.
