### ISSUE TITLE
K.A.S. 0.6.2 Winch related crash

### ISSUE THREAD

**Issue by NewbieUser123** [ihsoft/KAS#196]
**KSP**: 1.2.1 Windows

**Problem**: When the winch is completely retracted the game crashes

**Mods Installed**:
KAS 0.6.2
KIS 1.4.0
Module manager 2.7.5
CCK 1.2.1.0
TransfeWindowPlanner 1.6.0.0
KerbalEngineer 1.1.2.6
StationScience
KerbalAlarmClock 3.8.1.0

**Reproduction Steps**:
Playing in Career Mode.

Testing the new parts and actions from the recently installed mods (KIS,  KAS) just for see how it works.

In launch pad testing several mechanics, (grab, inventory, plug, unplug, attach, seeing the new containers).

When testing the winch I used the GUI for a connector in a container, everything was fine until I finished with the winch and tried to retract to its original state.

When it was completely retracted the game after a few seconds crashed. 

Log:

Have 4 logs according to each crash. And the output_log.txt

https://www.dropbox.com/sh/sx22vyk0c970kqm/AABHc2A4sLPs7_TTogMjj7xja?dl=0
https://www.dropbox.com/sh/p9g0hi4cn5n8wgd/AAA0TNYkbImjw1Xu5DZT8VUxa?dl=0
https://www.dropbox.com/sh/ki0zdi3rhkrhipz/AACJpnFBCY1eoQY62J5ZPYALa?dl=0
https://www.dropbox.com/sh/ybb8mrbyot2bz88/AAA_xUK-RZrjabPY7CWJwO24a?dl=0

https://www.dropbox.com/s/tqkvas16guoznd5/output_log.txt?dl=0

Also two screen shots of the testing site.

https://www.dropbox.com/s/p179x6bb6sde6t5/Captura%20de%20pantalla%202016-12-28%2019.20.20.png?dl=0

https://www.dropbox.com/s/ri8nelonpls4f0z/Captura%20de%20pantalla%202016-12-28%2019.21.20.png?dl=0

Thanks for the support.

**Comment by ihsoft** [comment]
Could you please capture `KSP.log` instead? `output_log.txt` is not useful.

Also, can you repeat the same problem doing the same steps or this problem shows up intermittently?

**Comment by NewbieUser123** [comment]
Hello,

Yes, I was playing without using KIS or KAS but the mods are installed. I repeat the same testing with the GUI and this  time I ejected the winch, then I retracted it and when it was full retracted I change the focus to point a kerbal who is standing right there and I got the crash.

here is the KSP LOG:
https://www.dropbox.com/s/haoprbigbpypkyl/KSP.log?dl=0

And the new crash:
https://www.dropbox.com/sh/xibbruki437joc2/AAD3irIhwzdGQcBZmirvdPfya?dl=0

**Comment by ihsoft** [comment]
Well, whatever I do it doesn't reproduce for me. If you could record a short video it would help.

**Comment by NewbieUser123** [comment]
Hello,

Yes, I have it here. The resolution is low but you can see it here:

https://www.dropbox.com/s/bdzbxstp39hde8r/2016-12-30%2018-52-43.mp4?dl=0

(The last part of the video is the moment of the crash, the recorder continue but I was viewing the crash message below)

As you can see I use this time both winches, playing around, when both were completely retracted I change the camera to the kerbal, try to point the winch and the game freezes and I had this message:

https://www.dropbox.com/s/rzkrf3xx2pe0nub/crash.png?dl=0

The new logs are here too:

KSP log: https://www.dropbox.com/s/wgmh93fuzd6thy2/KSP%20%282%29.log?dl=0
Crash report folder: https://www.dropbox.com/sh/cvllnsw6svqrn5k/AADHyc7ZjzFAYFT28dlpE7SQa?dl=0

Maybe is something with the camera focus when I point it to the kerbal, or when I point the cursor over the winch.

Thanks again and happy new year.

**Comment by ihsoft** [comment]
From the logs I see you use three extra mods: Kerbal Engineer, KAC, and StationScience. Just to ensure this is 100% not a mods conflict issue, please, remove them and check if you can reproduce the problem (no need to record another video). Also, please provide the ship design file so what we use exactly the same assembly.

I tried to reproduce as close as I could and no issue appeared:
https://www.youtube.com/watch?v=-vsYh6u9098&feature=youtu.be

**Comment by NewbieUser123** [comment]
Hello,

I'm very pleased to inform you that I change the version of the KSP to 1.2.2 and everything seems ok until now. 

Thasnk you very much for your support and your time, I'm going to continue testing the parts.

**Comment by ihsoft** [comment]
Glad to hear it!
