### ISSUE TITLE
Suggestion: crossfeed rule (pipes behaving like real pipes)

### ISSUE THREAD

**Issue by AstroMec** [ihsoft/KAS#198]
Is it possible that the pipes work as real KSP pipes so that they work even when "ObeyCrossfeed rule" is enabled? Because I think that it treats the pipes as if they were kind of docking ports. Thank you. #197 was the issue I had, but you kindly told me to check my crossfeed rule (which I then did, thank you for suggesting), but now it would become an enhancement.

**Comment by ihsoft** [comment]
As stated in #189, it _will not_ be fixed in old KAS. This is already fixed in KAS 1.0 which is going to replace the old KAS.

I leave this bug open to not have this issue raised again but I'd like to clearly note: fuel transfer in _old_ KAS works as it works, there are no plans to change it.
