### ISSUE TITLE
Career mode confusion

### ISSUE THREAD

**Issue by henryr0923** [ihsoft/KAS#200]
Maybe I am blind, but I am using the community tech tree and I can find all of the pieces for your mod except for the basic connector.

What tech node is it supposed to be in?!

**Comment by ihsoft** [comment]
What do you mean by "basic connector"?

**Comment by henryr0923** [comment]
Sorry, the connector to attach the winch to. I have the winch, but I can't use it for anything but EVAs and harpooning

**Comment by ihsoft** [comment]
The winch attaches to the parts via a normal attach node as any other regular part, no connector is needed. The other parts can be attached to the winch cable via a cPort part (CC-R2). The port lives in the Advanced Fuel Systems tech tree branch.
