### ISSUE TITLE
KSP v 1.3 crashes while loaded with KAS

### ISSUE THREAD

**Issue by MarkMaxMayne** [ihsoft/KAS#202]
KSP was updated to version 1.3 this week.  Remove all mods.  Add KAS manually.  KSP 1.3 crashes while loading.  Run KSP 1.3 without KAS then all of your spaceships with parts such as winches, connectors, etc. are deleted from your save file upon loading.

**Comment by ihsoft** [comment]
It's a known behavior. KAS 0.6.2 is not compatible with KSP 1.3, and this is being fixed.

Btw, the game crashes not because of KAS specifically. It's a new game's behavior for any mod that has custom parts but cannot load due to the missing/wrong assemblies.
