### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by Dragg0n** [ihsoft/KAS#203]
hi. Can I translate the mod in Russian. And if it works, will I send you a transfer?

**Comment by ihsoft** [comment]
Translation of the `KAS` mod is on the radar. However, I don't it's worth spending efforts on the old `KAS` which is being deprecated.

Are you going to translate the parts descriptions only? Because for the other strings there is no localization support yet.

**Comment by Dragg0n** [comment]
es, I just want to translate the name and the description. Under RSP 1.2 ... Russian

**Comment by Dragg0n** [comment]
Yes, I just want to translate the name and the description. Under RSP 1.2 ... Russian ****

**Comment by ihsoft** [comment]
Sure, feel free to do so.

**Comment by Dragg0n** [comment]
Thank you! If you get a decent translation, put a link. I hope people will like it.

**Comment by Dragg0n** [comment]
Translating these fields, got a problem. The description disappears in the game. Are there any conditions for compliance?

name = KASModulePort
name = KASModuleStrut 

Simple example of a replacement
name = KAS Данные модуля
name = KAS Характр. модуля

**Comment by ihsoft** [comment]
The module name is a name of the class of the assembly. Do not translate it. In general, there are many fields which values are not localizable. I'd suggest changing only the the string which you see in GUI.

**Comment by Dragg0n** [comment]
Ок

**Comment by Dragg0n** [comment]
https://cloud.mail.ru/public/GR7G/mmLw87nHq
Then it turns out to translate so much.

**Comment by Dragg0n** [comment]
I wanted to clarify
Tags = KIS KAS asparagus channel hose (lf line ox oxidizer pipe propellant pump tube cck-eva-items
Words for the filter? Are they subject to translation?

**Comment by Dragg0n** [comment]
https://cloud.mail.ru/public/2BQc/9oy8MJ2Ud - Download link

I translated what I could. Translated, according to the words and meaning of objects. There is no way to get to the buttons. If you display the button names and additional description in separate "sting" "char" variables in a separate file. Then I can fully translate.

**Comment by ihsoft** [comment]
Thanks. However, I think it makes sense to do the localization via the new KSP 1.3 functionality. When I start working on it, I'll get back to your localizations.

**Comment by ihsoft** [comment]
Actually, I've decided not to waste time on the old KAS localization. The 1.0 version will have the Russian localization out of the box.
