### ISSUE TITLE
Gigantor Solar Panels break on removal

### ISSUE THREAD

**Issue by Bluejay47** [ihsoft/KAS#208]
If I remove a gigantor solar panel, either in collapsed or expanded mode, and then place it on the ground it explodes. If I remove the panel and immediately transfer the panel to storage the panel transfers without exploding but breaks and is still broken if I remove it from storage. Am I doing something wrong or can these panels just not be detached?

Thanks,

**Comment by ihsoft** [comment]
It works fine to me when tested on the Kerbin launchpad. Where do you observe this issue? Can you reproduce it with the minimum set of the mods on the launchpad?

**Comment by Bluejay47** [comment]
I'll try to test it this weekend and let you know what I find.
