### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by FluffyLogic** [ihsoft/KAS#219]
1. Please add action group to stop running winch from retracting / extending cable. Currently only retract / extend are in action groups, only direct command in winch GUI stops it. I'm using AGX for named groups if it helps.
2. Please add stack-centered winch so payloads can be at center of craft (currently i have to take IW-50 and translate it to a side to offset any imbalance).

**Comment by ihsoft** [comment]
Not sure what do you mean by # 2. IW-50 has a "top" attach node which allows mounting it in the center of the craft.
