### ISSUE TITLE
Debug Key Conflict

### ISSUE THREAD

**Issue by DerpKerman** [ihsoft/KAS#222]
Debug key ctrl + k conflicts with KerbalKonstructs primary editor launch keys.

Solution: Hell if I know. or change debug key to something more obscure.
(Because k is pretty obvious for primary features on many mods, tertiary features such as debug menus probably shouldn't use it due to the high probability to conflict with other mods primary features)

**Comment by ihsoft** [comment]
It's for the KAS 0.9.*, right? That version is in a freeze mode. There will be no debug features in KAS 1.0.

**Comment by tonimark** [comment]
GOT THE SAME ISSUE HERE!
