### ISSUE TITLE
Allow to destroy item in containers and pouches.

### ISSUE THREAD

**Issue by evorios** [ihsoft/KAS#233]
Garbage accumulates in containers over time, and now it is difficult to destroy. I would like to see a button or a special panel in the interface of containers, or maybe a special shredder, with the encouragement of which you can destroy unnecessary details.
![screenshot7_](https://user-images.githubusercontent.com/1260935/45698623-7c8f4080-bb79-11e8-91ee-a7d90a1e8a99.png)

**Comment by ihsoft** [comment]
How about using the bomb? Disposing garbage is its main purpose. Pile up the unneeded items, place the bomb nearby and blow it up. Profit! A simple "Destroy" button doesn't seem very realistic.

**Comment by evorios** [comment]
No. I want to have shredder in my vessel to destroy items without EVA.

**Comment by ihsoft** [comment]
Well, making a non-physical "destroy" method is not what this mod needs. Those, who want doing it in aphysics way should use the bomb. Those who don't care can enable the `KIS` debug mode, it allows destroying items via the context menu.
