### ISSUE TITLE
KAS 1.0: RTS-1 doesn't see all the resources on the vessel

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KAS#240]
It seems the "direction" of the RTS-1 affects how the part detects the available resources/capacities. In the testbed below, the right RTS is set to the docked mode and the left one is used to transfer the resources. For some reason, the part sees Monopropellant and electricity from the landing can, but doesn't see its LOX reserve.
![image](https://user-images.githubusercontent.com/7295777/46652419-d7540080-cb57-11e8-8751-81c513470e87.png)
(Apologies for non-English locale)

**Comment by HaullyGames** [comment]
Hi @ihsoft 
I'm new on this project, but my question is
How the landing can can transfer monopropellant or electricity to a Oxidizer/Liquid tank?

Is it possible???
