### ISSUE TITLE
Fun parts in legacy KAS are not equipping

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KAS#251]
Need to be updated to `KIS 1.16`.

**Comment by Robsel** [comment]
Harpoon doesn't work and I really want to send a probe to Gilly and land with it. D:

**Comment by ihsoft** [comment]
The harpoon is not equippable part. This bug is for the equipping issue only.

**Comment by ihsoft** [comment]
In fact, this bug was created by a mistake. Even I can confuse KIS & KAS. Weird! Moving it to KIS.
