### ISSUE TITLE
Missing files trying to compile locally

### ISSUE THREAD

**Issue by TonkaCrash** [ihsoft/KAS#263]
Igor, 
I tried to download and compile KAS for 1.7 and ran into a missing file in the github project: KAS\Source\debug\KASDebugAdjustableAttribute.cs

**Comment by ihsoft** [comment]
Yeah, looks like `.gitignore` ignores files in any folder, not in the compile ones only. Will add when I'm back from a trip. Meanwhile, you can simply comment all those attributes. They are only needed for the KAS part adjustment tool. The mod will perfectly work without them.
