### ISSUE TITLE
It's seems that KAS v1.2 do not support KSP v1.7

### ISSUE THREAD

**Issue by codeghosts** [ihsoft/KAS#264]
Hello! I am a fan of your KAS and KIS plugins .  
I found a problem with KAS v1.2 when KSP was updated to v1.7.
Right click on the winch , but the function menu is not displayed as usual , and in fact , other modules in this plugin have the same problem . But they all works well when I roll back the game version to v1.6 .

**Comment by xurei** [comment]
Same issue for me
