### ISSUE TITLE
No pipe or other connectors.

### ISSUE THREAD

**Issue by leonidiudakov** [ihsoft/KAS#267]
I am playing 1.6.1 and I have the joint sockets, but I don't see any pipes/connectors (I have KIS too). When any kerbal goes on EVA (pilot, scientist, engineer), and I right-click any socket (I get as close as I can), It shows no "Connect" button or something like that.(1) Even if I enable "Advanced Tweakables". Help, I need to connect my rovers! :) 
Also, the "FlexPipe" folder is empty.(2+3)
1:
![Screenshot_20190428_200241](https://user-images.githubusercontent.com/18710803/56874763-f9787780-69f0-11e9-8f09-9c83835efdb6.png)
2:
![Screenshot_20190428_192457](https://user-images.githubusercontent.com/18710803/56874001-7bfe3880-69eb-11e9-84f4-96ffcd440f8e.png)
3:
![Screenshot_20190428_192526](https://user-images.githubusercontent.com/18710803/56874003-828cb000-69eb-11e9-9088-7a7f8ed6351b.png)

**Comment by leonidiudakov** [comment]
Add: How to equip the wrench?

**Comment by leonidiudakov** [comment]
![Screenshot_20190428_200241](https://user-images.githubusercontent.com/18710803/56874763-f9787780-69f0-11e9-8f09-9c83835efdb6.png)

**Comment by ihsoft** [comment]
Legacy KAS part have been deprecated in v1.2. The new parts follow different paradigm. You cannot create a pipe between two ports any longer. There always must be a "source" part that provides the pipe, cable or hose reserve. See [this Wiki](https://github.com/ihsoft/KAS/wiki/Legacy-parts-destiny).

**Comment by leonidiudakov** [comment]
What about the Wrench? When I right-click and click "Equip", nothing happens.

**Comment by ihsoft** [comment]
Wrench is a KIS part. KIS mods didn't update recently, so if you have troubles, it's likely a mods conflict issue in your setup. Please, raise this issue on the KIS forum with the screenshots and logs attached. IIRC there was a similar report already.

**Comment by leonidiudakov** [comment]
Thank you very much!!!!!
