### ISSUE TITLE
[Issue/Bug] Stuck in flexible corridor connect mode (KPBS)

### ISSUE THREAD

**Issue by TacoCraftxD** [ihsoft/KAS#275]
([Original Report+"Answer" from KPBS owner](https://github.com/Nils277/KerbalPlanetaryBaseSystems/issues/103))

When entering into corridor connect mode, and then using vesselmover's "Spawn Vessel" tool you get stuck in corridor connect. I think this is because when spawning a new vessel you focus it, and then i managed to kill the kerbal that originally started it. And so i am stuck in connect mode.
![Example](https://user-images.githubusercontent.com/32072697/59914040-cadbb380-9419-11e9-8825-4f553056945e.png)
Look at the Light/Gear/Brake buttons for example.

The ESC key doesn't work either, i have to use the button on the top. Also copying the savegame doesn't work either.

Also just noticed that when right-clicking i cant click any buttons. The menu comes up, but no buttons:
![KSP_x64_hl7Oj95722](https://user-images.githubusercontent.com/32072697/59915653-6d496600-941d-11e9-95ef-0a62ab27eefe.png)

Save (Creative):
[Bases1.zip](https://github.com/Nils277/KerbalPlanetaryBaseSystems/files/3314202/Bases1.zip)

**Comment by ihsoft** [comment]
Why do you spawn vessels when in the connection mode? The connection mode requires mouse input. So, it must be ended before doing anything else that mayo require mouse or player focus.

If I have time I'll try installing VesselMover and see if anything can be done here, but for now it seems like another mods conflict issue.

**Comment by TacoCraftxD** [comment]
I am spawning vessels because i am trying to make a cool habitat instead of flying the rocket up there and stuff. 

Is there any way to fix the savegame you think?

**Comment by ihsoft** [comment]
Best bet would be loading the save game _before_ the problem happen. The are too many use-cases  to cover. You may try finding states `Linking` in the save game file and changing them to `Available`. But it will only solve a part of the problem. Try sharing your save game on the KAS forum. Someone may volunteer to go over it and fixing.

And as a rule of thumb, take this: never start another action before completing the previous one. If you started any action that shows a status string at the top of the screen (e.g. KAS linking), make sure you've completed it before starting anything else. This approach will help preventing issues with any third party mod, not only KAS.

**Comment by TacoCraftxD** [comment]
Got it, thanks 👍

**Comment by TacoCraftxD** [comment]
Changing `Linking` to `Available` fixed it!
