### ISSUE TITLE
Updating to v1.9.1

### ISSUE THREAD

**Issue by StarterCraft** [ihsoft/KAS#288]
Will your super useful mod be updated for KSP version 1.9.1? It's highly requested! 

Thanks!

**Comment by michgauz** [comment]
Yes this would be great!
Is it planned ?

Thanks for your work

**Comment by ihsoft** [comment]
The current version of the mod is working fine with the latest KSP. The only issue is MiniAVC complaining about the version change. I plan to remove this check in the next release. Meanwhile, feel free to install and start using the mod.
