### ISSUE TITLE
Cant find KAS on ckan.

### ISSUE THREAD

**Issue by misieck** [ihsoft/KAS#293]
KSP 1.9.1, ckan 1.27.2
Im not sure if its a problem with KAS or with ckan?

**Comment by ihsoft** [comment]
The problem is in CCK dependency which is marked incompatible with `1.9.1`. In fact it's _is_ compatible, but CKAN doesn't know it, so it hides all mods that depends on `CCK`. `KIS` and `KAS` included.

As a workaround, mark version `1.8` as compatible.

**Comment by ihsoft** [comment]
It should be visible now.
