### ISSUE TITLE
Please stop shipping MiniAVC.dll

### ISSUE THREAD

**Issue by HebaruSan** [ihsoft/KAS#295]
MiniAVC doesn't work anymore. @linuxgurugamer gave up on maintaining it and set all his mods to depend on ZeroMiniAVC in KSP-CKAN/NetKAN#7690 to reduce the number of crashes. This user was affected by this and the crash went away after he installed ZeroMiniAVC:

- https://forum.kerbalspaceprogram.com/index.php?/topic/195103-ksp-crashes-on-start-when-using-mods-installed-via-cka/

Tagging @ihsoft because not everyone has GitHub notifications turned on for everything.

**Comment by linuxgurugamer** [comment]
Just an FYI, MiniAVC depended on using threads, which are incompatible with Unity.  While it worked for the earlier version, it broke badly when 1.8 and the new version of Unity was released.  While I did manage to fix it, there was no easy way to ensure that all mods got updated.  So I deprecated it, and rely on ZeroMiniAVC to clean up the mess

**Comment by ihsoft** [comment]
Sad to hear that. Significant part of the userbase get my mods from Curse, and for them a version tracking mod is a really cool thing (in CKAN and Spacedock there are own ways to notify the users). If you say MiniAVC has that major issue, I think my only bet is writing own version checking mechanism. Thanks for letting me know.

For the record, I really regret that this mod support was dropped. At the moment its way of tracking versions is a "defacto" standard.

**Comment by HebaruSan** [comment]
> Thanks for letting me know.

No problem.

> I think my only bet is writing own version checking mechanism. [...] For the record, I really regret that this mod support was dropped. At the moment its way of tracking versions is a "defacto" standard.

If you find it well suited, maybe you could adopt, fix, and release MiniAVC, since it is now technically abandoned? Agreed that it wasn't great to have such a widely used mod abruptly end-of-lifed with no viable replacement.

**Comment by linuxgurugamer** [comment]
I do have the problem fixed, if you feel that the full AVC isn't good enough, I could release a v2 version.  It was just the nightmare of having both fixed and unfixed versions which made me decide to drop it.

**Comment by linuxgurugamer** [comment]
I'm working today (big release), but if I get time, I'll get it updated with a new name.  Give me a day or so, worst case is that I'll do it on-stream tomorrow

**Comment by linuxgurugamer** [comment]
You can get the new MiniAVC-V2.dll from here:

https://github.com/linuxgurugamer/KSPAddonVersionChecker/releases/tag/1.4.1.5

**Comment by ihsoft** [comment]
Cool, this sounds like a great approach. I'll upgrade my mods to the new version.

**Comment by HebaruSan** [comment]
Sounds like this issue has served its purpose, no need to keep it open. Cheers to all!
