### ISSUE TITLE
Decoupling near winch connected in editor causes the winch to break in to two separate vessels.

### ISSUE THREAD

**Issue by Fatgecko5** [ihsoft/KAS#297]
Steps to reproduce:

KSP version: 1.8.1
KAS version: 1.6

Provided craft file is set up for this.
Note the direction of the decoupler on top. 
Launch vessel and decouple the decoupler. 
Note how the struts stay intact and the winch stays locked
Go back to the VAB and put the decoupler upside down
Repeat decoupling in flight
Note how the struts break and there are now two distinct crafts connected with the winch and a cable length of 0.
[KAS bug report.craft.txt](https://github.com/ihsoft/KAS/files/4905082/KAS.bug.report.craft.txt)

**Comment by ihsoft** [comment]
Could you please also provide a short video to demonstrate the sequence? Logs would help too.

**Comment by Fatgecko5** [comment]
Here is my KSP log. From launch I went straight to the VAB and made the example craft then straight to the video so hopefully there isn't too much useless stuff in there. Lots of mod messages really
[KSP.log](https://github.com/ihsoft/KAS/files/4907803/KSP.log)

As well as a short video: [https://youtu.be/-e5FgsZa90o](url)

**Comment by 7ranceaddic7** [comment]
Bad YouTube link.

**Comment by ihsoft** [comment]
So, the problem is actually wider. Any decoupling, made by not KAS, results in resetting of the DOCKING mode on _all_ the `KAS` parts. It's not winch specific. Simple steps to reproduce:
1. Have a linked KAS link in DOCKED mode.
2. Use KIS tool to detach any part on any other vessel.
3. The KAS link gets reset to UNDOCKED.

**Comment by 7ranceaddic7** [comment]
I just watch the corrected youtube.

Did you notice what happened with the PAW?

When the decoupling occurs the sprite line between the part and PAW goes straight up off-screen.

I'm not a blender expert (I don't even qualify as a noob.) But I'll be there is a collider that gets "decoupled" that shouldn't.

**Comment by Fatgecko5** [comment]
When I was debugging it I kind of thought it was a deeper problem than the fix I did but I wasn't really sure. That's unfortunate, glad I saved you debugging time at least.

For now I compiled a version of KAS with my "fix" which works well enough for the features I'm using at the moment

**Comment by Fatgecko5** [comment]
Fixed by this pull request https://github.com/ihsoft/KAS/pull/298#issuecomment-662840917
