### ISSUE TITLE
Setup career, enjoy, land on duna, add refuel unit, connect to base ... then ...

### ISSUE THREAD

**Issue by alexbfr** [ihsoft/KAS#300]
Back into KSP after 2 years, was *so* satisfied to have established a Duna base, was about to connect refueling unit with base ... then ...  you guess it.

**Comment by alexbfr** [comment]
Great ideas, guys. I'd so glad to help with coding, but to take away something that was *granted* - yeah.

**Comment by ihsoft** [comment]
If you want to discuss this mod, please use the forum.
