### ISSUE TITLE
the winch not apeared in construction menu

### ISSUE THREAD

**Issue by guile2-01** [ihsoft/KAS#301]
the winch parts no apear in the game

**Comment by ihsoft** [comment]
Could you please share the log?

**Comment by guile2-01** [comment]
[MMPatch.log](https://github.com/ihsoft/KAS/files/5750630/MMPatch.log)
[ModuleManager.log](https://github.com/ihsoft/KAS/files/5750631/ModuleManager.log)

**Comment by ihsoft** [comment]
[This log](https://github.com/ihsoft/KIS/wiki/Troubleshooting#how-to-get-the-games-log-file), please.

**Comment by ihsoft** [comment]
Also, please add a screenshot from the editor.

**Comment by guile2-01** [comment]
okay this log file no?

**Comment by ihsoft** [comment]
There is nothing attached. Please, upload the log to some sharing service and only provide a link here. The logs are usually very big.

**Comment by guile2-01** [comment]
https://drive.google.com/file/d/1yFAh2OFuC6GtmZH6lLyX43gCSX3dS1_H/view?usp=sharing

okay and this?

**Comment by ihsoft** [comment]
The file is not accessible. Please, change sharing settings to "anyone".

**Comment by guile2-01** [comment]
https://drive.google.com/file/d/1yFAh2OFuC6GtmZH6lLyX43gCSX3dS1_H/view?usp=drivesdk

Try now

**Comment by ihsoft** [comment]
So, I don't see anything wrong related to `KAS` ibn the log. However, I see many critical errors related `Firespitter` and `DaMichel's CargoBays` mods. Try removing these mods and re-launch the game. If there are problems, please share the log again. At this point your log shows that the game is in a very bad state.

**Comment by ihsoft** [comment]
Please, let me know if you get this issue resolved so that we can close it.

**Comment by guile2-01** [comment]
the problem continues

LOG FILE: https://drive.google.com/file/d/1fwif7kCwgzt1Rr9HOhpt9UFZTvDxZc_v/view?usp=sharing

**Comment by ihsoft** [comment]
So, now I see the problem. You've improperly installed KAS:
```
[LOG 14:31:29.787] AssemblyLoader: Loading assembly at C:\GOG Games\Kerbal Space Program\GameData\GameData\CommunityCategoryKit\CCK.dll
[LOG 14:31:29.806] AssemblyLoader: Loading assembly at C:\GOG Games\Kerbal Space Program\GameData\GameData\KAS\Plugins\KAS-API-v2.dll
[LOG 14:31:29.828] AssemblyLoader: Loading assembly at C:\GOG Games\Kerbal Space Program\GameData\GameData\KAS\Plugins\KAS.dll
[LOG 14:31:29.858] AssemblyLoader: KSPAssembly 'KAS' V1.7.0
[LOG 14:31:29.859] AssemblyLoader: Loading assembly at C:\GOG Games\Kerbal Space Program\GameData\GameData\KAS\Plugins\KSPDev_Utils.2.4.dll
[LOG 14:31:29.877] AssemblyLoader: Loading assembly at C:\GOG Games\Kerbal Space Program\GameData\GameData\KAS\Plugins\MiniAVC-V2.dll
```

Note the duplicated path: `GameData\GameData`. There must be only one `GameData`. I recommend you using [CKAN](https://github.com/KSP-CKAN/CKAN/releases) to avoid this kind of problems in the future.

**Comment by guile2-01** [comment]
Thanks
