### ISSUE TITLE
Can't add KAS parts to stock cargo containers

### ISSUE THREAD

**Issue by JotaRata** [ihsoft/KAS#322]
Probably you already know this problem but I couldn't find it over here.

Basically you can't put KAS parts like the winch and connector ports to the stock cargo containers.

Here's a video:

![Kerbal Space Program 2021-06-23 15-19-57 (online-video-cutter com)](https://user-images.githubusercontent.com/36273501/123159328-e62f8e00-d43a-11eb-8916-dac13ec3f032.gif)

**Comment by ihsoft** [comment]
This is a known issue. In fact, there is a lot of effort currently being put into solving this problem. This has repeatedly surfaced on the forum.

**Comment by ihsoft** [comment]
In the new version you can.
