### ISSUE TITLE
Error in the logs when an inactive vessel gets in range

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/KAS#326]
When a packed vessel with a KAS part gets created, it can start acting on the vessel decoupling events. It may prevent global coupling check:

```
[LOG 00:30:23.221] [Part:KAS.W2 (id=C4294796932)#Module:2] Scheduling global coupling check...
[ERR 00:30:23.221] Coroutine couldn't be started because the the game object 'KAS.W2' is inactive!
```

**Comment by RafaelDominiquini** [comment]
This message appears with no KAS parts installed in the vessel. Neither I have any inactive vessel in range, with or without KAS parts! 
This message appears with my first launch in Carrer or any saved game. Appears every time I perform the first decoupling event (planned or unplanned) of some vessel I'm controlling. Subsequent decoupling events are OK!

Thanks.
