### ISSUE TITLE
GUI large and oddly shaped, hard to fit in the stock screen

### ISSUE THREAD

**Issue by 5thHorseman** [ihsoft/KAS#79]
Most mods with a GUI, it's roughly square shaped or configurable. KAS's is wide and short, almost like a toolbar in a browser. The problem (other than making me think of browser toolbars. _shudder_) is that there is no good place to put this on your screen. Either you to put it at the top (where there are at least 3 stock gui elements) or bottom (where there are at least 2 stock gui elements, 3 if you have Kerbals on board), or somewhere in the middle covering your ship which (because you're using KAS) also has a lot of clickable elements.

I'm not sure the best thing to do about this, but maybe giving each winch its own gui would be a start. Rework it so it's more squarish and maybe allow us to hide controls we don't need to make it auto-size smaller.

**Comment by ihsoft** [comment]
I'd suggest this request is about winch GUI.
