### ISSUE TITLE
Two ships controlled after un-docking (Struts?)

### ISSUE THREAD

**Issue by ravenousjoe** [ihsoft/KAS#95]
After docking with a ship, I put Bob on EVA to attach end points on both vessels, then link them for some extra stability during a transfer out to Dres. After un-docking, landing, performing science, and take-off to rendezvous, I was then within 2.3 kms of the transfer stage. At this point I noticed it was performing the same maneuvers that the lander was performing thus making docking impossible without switching to that craft and turning off it's torque producing parts. The ship was not affected by engine throttle, only pitch, roll, and yaw. This same issue has never happened prior to installing KAS.

List of Mods I am using:
B9 Aerospace
KAS
Kerbal Alarm
Ferram
Procedural Fairings
NavyFish's Docking alignment

**Comment by ihsoft** [comment]
Is it still reproducible?
